--发票信息请求表
CREATE TABLE "yxy_invoice_information_request" (
  "invoice_id" BIGSERIAL,
  "invoice_flow_number" varchar(100) NOT NULL COLLATE "default",
  "bill_point_code" varchar(100) COLLATE "default",
  "invoice_type_code" varchar(100) COLLATE "default",
  "apply_way" varchar(100) COLLATE "default",
  "buy_id" int4,
  "sale_id" int4,
  "mobile" varchar(100) COLLATE "default",
  "email" varchar(100) COLLATE "default",
  "payee" varchar(100) COLLATE "default",
  "ssuer" varchar(100) COLLATE "default",
  "manager" varchar(100) COLLATE "default",
  "bill_type" int4 NOT NULL,
  "original_invoice_code" varchar(100) COLLATE "default",
  "original_invoice_number" varchar(100) COLLATE "default",
  "remarks" varchar(255) COLLATE "default",
  "bill_channel" varchar(100) COLLATE "default",
  "apply_bill_date" timestamp(6) NULL,
  "total_amout" numeric(10,2),
  "total_tax_amout" numeric(10,2),
  "price_tax_total" numeric(10,2),
  "bill_status" int4 DEFAULT 0,
  "created_at" timestamp(6) NOT NULL,
  "updated_at" timestamp(6) NULL,
  "request_data" text COLLATE "default",
  "customer_id" int4
);